[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "docs/"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
  
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    # run E2E tests against the deployed URL
    record = true
    group = 'deployed'
  [plugins.inputs.postBuild]
    # run E2E tests against locally built site
    # before deploying it
    enable = true
    record = true
    group = 'built'